apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: garouter-uaa
  namespace: YOUR_NAMESPACE
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  externalName: garouter-uaa
  parameters:
    xsappname: i503557-garouter
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:        
        - "https://CLUSTER_DOMAIN/login/callback"
    scopes:
      - name: "$XSAPPNAME.admin"
        description: Admin
    role-templates:
      - name: admin
        description: Admin
        scope-references:
          - "$XSAPPNAME.admin"
    role-collections:
      - name: Approuterkyma
        description: kyma approuter role
        role-template-references:
          - "$XSAPPNAME.admin"
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: destination-service-1
  namespace: YOUR_NAMESPACE
spec:
  externalName: destination-service-1
  serviceOfferingName: destination
  servicePlanName: lite